server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri /index.html =404;
    }

    location /api/ {
        proxy_pass https://backend-production-64fd.up.railway.app/;
        proxy_ssl_server_name on;
        proxy_set_header Host backend-production-64fd.up.railway.app;
        proxy_set_header X-Real-IP $remote_addr;
    }
}