services:

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite+aiosqlite:////app/data/database.db
      - LLM_API_KEY=${LLM_API_KEY?None}
      - JWT_SECRET=${JWT_SECRET?super-duper-token}
      - REFRESH_TOKEN_EXPIRE_DAYS=${REFRESH_TOKEN_EXPIRE_DAYS?30}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES?30}
      - ALGORITHM=HS256
      - DEBUG=True
    volumes:
      - ./backend:/app/backend
    networks:
      - app-network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend-dev:
    image: oven/bun:1
    working_dir: /app/frontend
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "5173:5173"
    networks:
      - app-network
    command: sh -c "bun install && bun run dev"


  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge